import Head from "next/head";
import { Inter } from "@next/font/google";
import PopUp from "@/components/PopUp";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [showPopUp, setShowPopUp] = useState(false);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {showPopUp && <PopUp setShowPopUp={setShowPopUp} />}
        <button className="main-btn" onClick={() => setShowPopUp(true)}>
          Click Here
        </button>
      </main>
    </>
  );
}
